[ "v-n"    `110 ] ':n' define
[ "v-s"    `111 ] ':s' define
[ "v-c"    `112 ] ':c' define
[ "v-p"    `113 ] ':p' define
[ "v-f"    `114 ] ':f' define
[ "v-vn"   `120 ] 'type?' define
[ "nn-n"   `200 ] '+' define
[ "nn-n"   `201 ] '-' define
[ "nn-n"   `202 ] '*' define
[ "nn-n"   `203 ] '/' define
[ "nn-n"   `204 ] 'rem' define
[ "n-n"    `205 ] 'floor' define
[ "nn-n"   `206 ] '^' define
[ "n-n"    `207 ] 'log' define
[ "n-n"    `208 ] 'log10' define
[ "nn-n"   `209 ] 'log<n>' define
[ "nn-n"   `210 ] 'shift' define
[ "nn-n"   `211 ] 'and' define
[ "nn-n"   `212 ] 'or' define
[ "nn-n"   `213 ] 'xor' define
[ "-n"     `214 ] 'random' define
[ "n-n"    `215 ] 'sqrt' define
[ "nn-f"   `220 ] '<' define
[ "nn-f"   `221 ] '>' define
[ "nn-f"   `222 ] '<=' define
[ "nn-f"   `223 ] '>=' define
[ "vv-f"   `224 ] '=' define
[ "vv-f"   `225 ] '<>' define
[ "fpp-"   `300 ] 'if' define
[ "p-"     `301 ] 'while-true' define
[ "p-"     `302 ] 'while-false' define
[ "np-"    `303 ] 'repeat' define
[ "p-"     `305 ] 'invoke' define
[ "vp-v"   `306 ] 'dip' define
[ "vp-v"   `307 ] 'sip' define
[ "vpp-?"  `308 ] 'bi' define
[ "vppp-?" `309 ] 'tri' define
[ "pp-"    `400 ] 'copy' define
[ "pn-n"   `401 ] 'fetch' define
[ "npn-"   `402 ] 'store' define
[ "-p"     `403 ] 'request' define
[ "p-"     `404 ] 'release' define
[ "-"      `405 ] 'collect-garbage' define
[ "p-n"    `406 ] 'get-last-index' define
[ "np-"    `407 ] 'set-last-index' define
[ "v-vv"   `500 ] 'dup' define
[ "v-"     `501 ] 'drop' define
[ "vV-Vv"  `502 ] 'swap' define
[ "vV-vVv" `503 ] 'over' define
[ "vV-VvV" `504 ] 'tuck' define
[ "vV-V"   `505 ] 'nip' define
[ "-n"     `506 ] 'depth' define
[ "...-"   `507 ] 'reset' define
[ "s-f"    `601 ] 'function-exists?' define
[ "s-p"    `602 ] 'lookup-function' define
[ "s-"     `603 ] 'hide-function' define
[ "ss-n"   `700 ] 'find' define
[ "pnn-p"  `701 ] 'subslice' define
[ "s-f"    `702 ] 'numeric?' define
[ "v-v"    `800 ] 'to-lowercase' define
[ "v-v"    `801 ] 'to-uppercase' define
[ "s-"     `900 ] 'report-error' define
[ "n-n"    `1000 ] 'sin' define
[ "n-n"    `1001 ] 'cos' define
[ "n-n"    `1002 ] 'tan' define
[ "n-n"    `1003 ] 'asin' define
[ "n-n"    `1004 ] 'acos' define
[ "n-n"    `1005 ] 'atan' define
[ "n-n"    `1006 ] 'atan2' define

[ #100 ] 'NUMBER' define
[ #200 ] 'STRING' define
[ #300 ] 'CHARACTER' define
[ #400 ] 'POINTER' define
[ #500 ] 'FLAG' define
