default:
	cat parable.coffee pre.coffee > a.coffee
	coffee -bc a.coffee
	cat script-header a.js > pre
	chmod +x pre
	rm a.js a.coffee
#	cat parable.coffee listener.coffee > a.coffee
#	coffee -bc a.coffee
#	cat script-header a.js > listener
#	chmod +x listener
#	rm a.js a.coffee
