MD = ../tools/Markdown.pl

default:
	$(MD) arrays.md                  >html/arrays.html
	$(MD) bytecodes.md               >html/bytecodes.html
	$(MD) characters.md              >html/characters.html
	$(MD) comments.md                >html/comments.html
	$(MD) compiler_implementation.md >html/compiler_implementation.html
	$(MD) datatypes.md               >html/datatypes.html
	$(MD) flags.md                   >html/flags.html
	$(MD) loops_and_conditionals.md  >html/loops_and_conditionals.html
	$(MD) memory_model.md            >html/memory_model.html
	$(MD) numbers.md                 >html/numbers.html
	$(MD) pointers.md                >html/pointers.html
	$(MD) prefixes.md                >html/prefixes.html
	$(MD) quick_reference.md         >html/quick_reference.html
	$(MD) quotations.md              >html/quotations.html
	$(MD) recursion.md               >html/recursion.html
	$(MD) stack_implementation.md    >html/stack_implementation.html
	$(MD) stdlib.md                  >html/stdlib.html
	$(MD) strings.md                 >html/strings.html
	$(MD) variables_and_values.md    >html/variables_and_values.html
