# Standard Python3 implementation to use
# (This does not needsto support the requests library)
PY = pypy3

# Alternate Python3 implementation to use
# (This needs to support the requests library)
PYALT = python3
